# Generated by Django 5.2.10 on 2026-01-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cart_id", models.IntegerField()),
                ("book_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
